language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
